import type { Track, TrackChapter } from './tracks'

/**
 * Trilha "Carisma e flerte": 500 niveis, 20 capitulos de 25.
 *
 * A ordem e o produto. Cada nivel pede quase o mesmo que o anterior, com um
 * grao a mais de exposicao — a escada tem que ser imperceptivel para nao
 * frustrar. Os niveis ousados (o) aparecem espalhados como picos, e os que
 * podem terminar em um "nao" (n) avisam isso antes.
 *
 * O id de cada nivel e `capitulo-NN`. Ele vai para o banco, entao reordenar
 * dentro de um capitulo muda o significado do progresso ja salvo: acrescente
 * no fim do capitulo em vez de inserir no meio.
 */

/**
 * [titulo, o que fazer, execucoes (1 a 3), marcas]
 * Marcas: o = ousado, n = pode ouvir nao, e = autoestima, k = o teste de
 * nivelamento nunca pula (ponto fraco que precisa de treino).
 */
type Raw = [string, string, 1 | 2 | 3, string?]

function chapter(
  id: string,
  name: string,
  icon: string,
  note: string,
  raw: Raw[],
): TrackChapter {
  return {
    id,
    name,
    icon,
    note,
    steps: raw.map(([title, what, needs, flags = ''], i) => ({
      id: `${id}-${String(i + 1).padStart(2, '0')}`,
      name: title,
      what,
      needs,
      bold: flags.includes('o'),
      rejectionLinked: flags.includes('n'),
      esteem: flags.includes('e'),
      keep: flags.includes('k'),
    })),
  }
}

export const CARISMA: Track = {
  id: 'carisma',
  name: 'Carisma e flerte',
  icon: '🗺️',
  blurb: 'Do bom dia ao convite, um passo por dia',
  chapters: [
    chapter('olhar', 'Olhar e sorrir', '👀', 'Nenhuma palavra ainda. O corpo aprende que olhar não machuca.', [
      ['Olhar no espelho', 'Olhe nos seus próprios olhos no espelho por 10 segundos, sem desviar.', 3],
      ['Sorrir para o espelho', 'Sorria para você mesmo no espelho por 5 segundos, um sorriso de verdade.', 2],
      ['Andar sem o celular', 'Caminhe 5 minutos na rua sem mexer no celular, olhando em volta.', 3],
      ['Cabeça erguida', 'Ande um quarteirão inteiro com o queixo reto e os ombros abertos.', 3],
      ['Ver rostos', 'Na rua, olhe rapidamente o rosto de 10 pessoas que passarem.', 2],
      ['Três coisas boas', 'Antes de dormir, anote 3 coisas que você fez bem hoje, por menores que sejam.', 3, 'e'],
      ['Meio sorriso', 'Ao cruzar alguém, dê um meio sorriso, mesmo que a pessoa não veja.', 3],
      ['Olhar o atendente', 'Ao pagar algo, olhe no rosto de quem te atende por 1 segundo.', 3],
      ['Aceno com a cabeça', 'Faça um aceno leve com a cabeça para alguém que cruzar seu olhar.', 3],
      ['Segurar 2 segundos', 'Quando cruzar o olhar com alguém, segure 2 segundos antes de desviar.', 3],
      ['Sorrir de volta', 'Quando alguém sorrir para você, sorria de volta sem desviar o olhar.', 2],
      ['Sorrir primeiro', 'Olhe para um desconhecido e sorria antes dele.', 3],
      ['Sentar de frente', 'Num café ou praça, sente de frente para o movimento, não para a parede.', 2],
      ['Parar na porta', 'Ao entrar num lugar, pare um segundo na porta e olhe o ambiente antes de seguir.', 3],
      ['Olhar 3 segundos', 'Sustente o olhar de alguém por 3 segundos e sorria.', 3],
      ['Ocupar espaço', 'Fique 10 minutos sentado em público com as costas no encosto e os braços soltos, sem se encolher.', 2],
      ['Trajeto sem fone', 'Faça um trajeto inteiro sem fones de ouvido, disponível ao mundo.', 2],
      ['Arrumado para você', 'Saia de casa arrumado como se fosse a um lugar importante: roupa boa, cabelo feito, perfume.', 2, 'e'],
      ['Sorrir para uma mulher', 'Cruze o olhar com uma mulher, sorria de leve e siga seu caminho.', 3],
      ['Deixar o outro desviar', 'Quando cruzar o olhar com alguém, deixe a outra pessoa desviar primeiro.', 3],
      ['Comer sozinho', 'Faça uma refeição sozinho num restaurante, sem usar o celular.', 1, 'o'],
      ['Sorriso no elevador', 'No elevador, olhe para quem entrou e sorria.', 2],
      ['Esperar sem tela', 'Numa fila ou sala de espera, espere sem pegar o celular.', 2],
      ['Cinco olhares', 'Num lugar cheio, cruze o olhar com 5 pessoas diferentes, sorrindo.', 2],
      ['No meio da praça', 'Fique 2 minutos parado, tranquilo, no meio de uma praça ou saguão movimentado.', 1, 'o'],
    ]),

    chapter('cumprimentos', 'Bom dia, boa tarde', '☀️', 'Cumprimentar é a menor conversa que existe. Aqui ela vira hábito.', [
      ['Bom dia em casa', 'Dê bom dia olhando nos olhos para a primeira pessoa que encontrar no dia.', 3],
      ['Bom dia ao porteiro', 'Diga "bom dia" ao porteiro ou segurança do prédio.', 3],
      ['Boa tarde no caixa', 'Diga "boa tarde" ao caixa antes que ele fale primeiro.', 3],
      ['Bom dia ao motorista', 'Diga "bom dia" ao motorista do ônibus ou do carro de aplicativo.', 3],
      ['Tchau com sorriso', 'Ao sair de uma loja, diga "valeu, bom dia!" sorrindo.', 3],
      ['Boa noite na chegada', 'Ao chegar num restaurante ou lanchonete, diga "boa noite" a quem te recebe.', 2],
      ['Bom dia no elevador', 'Diga "bom dia" a quem estiver no elevador.', 3],
      ['Voz que se ouve', 'Diga um cumprimento alto o bastante para ninguém pedir para repetir.', 3],
      ['O vizinho de sempre', 'Cumprimente um vizinho com quem você nunca falou.', 2],
      ['Falar primeiro', 'Seja o primeiro a dizer "oi" para um conhecido.', 3],
      ['Tudo bem de verdade', 'Depois do bom dia, pergunte "tudo bem?" e espere a resposta de verdade.', 3],
      ['Bom dia com nome', 'Cumprimente alguém usando o nome: "bom dia, Marta".', 3],
      ['Aperto de mão firme', 'Cumprimente alguém com aperto de mão firme, olhando nos olhos.', 2],
      ['Oi na academia', 'Cumprimente alguém na academia ao chegar.', 3],
      ['Bom dia ao grupo', 'Ao chegar no trabalho ou na aula, dê "bom dia" ao grupo em voz alta.', 2],
      ['Bom dia a uma mulher', 'Diga "bom dia" a uma atendente, vizinha ou colega, sorrindo.', 3],
      ['Bom dia na rua', 'Diga "bom dia" a um desconhecido que passar perto, numa rua tranquila.', 3],
      ['Bom dia para você', 'Ao acordar, diga no espelho "bom dia, [seu nome]", olhando nos seus olhos.', 2, 'e'],
      ['Bom trabalho', 'Ao sair de um atendimento, diga "bom trabalho pra você!".', 3],
      ['Dia bonito, né?', 'Comente com alguém: "dia bonito hoje, né?".', 3],
      ['Promessa cumprida', 'Prometa a si mesmo algo pequeno hoje (acordar no horário, treinar, ler 10 páginas) e cumpra.', 3, 'e'],
      ['Boa noite, pessoal', 'Ao chegar numa sala com desconhecidos, diga "boa noite, pessoal".', 2],
      ['Dez cumprimentos', 'Num único dia, cumprimente 10 pessoas diferentes.', 1],
      ['Oi para uma desconhecida', 'Diga "oi, boa tarde" a uma mulher desconhecida num contexto natural, como fila ou elevador.', 2],
      ['Bom dia ao vagão', 'Ao entrar num ônibus ou vagão, diga "bom dia" em voz alta para todos.', 1, 'o'],
    ]),

    chapter('gentilezas', 'Obrigado e gentilezas', '🙏', 'Gentileza abre portas sem pedir nada em troca. É carisma sem risco.', [
      ['Obrigado olhando', 'Diga "obrigado" olhando nos olhos da pessoa, não para o produto.', 3],
      ['Obrigado com nome', 'Leia o crachá e agradeça pelo nome: "obrigado, Carlos".', 3],
      ['Segurar a porta', 'Segure a porta para alguém e sorria quando a pessoa passar.', 3],
      ['Pode ir', 'Dê passagem a alguém com um gesto e um "pode ir".', 2],
      ['Gentil com você', 'Quando errar algo hoje, fale com você como falaria com um amigo, não como um carrasco.', 2, 'e'],
      ['Valeu, motorista', 'Ao sair do ônibus ou do carro, diga "valeu, obrigado!".', 3],
      ['Agradecer o detalhe', 'Agradeça algo específico: "obrigado por ter separado isso pra mim".', 3],
      ['Perguntar o nome', 'Pergunte o nome de um atendente que você vê sempre.', 2],
      ['Lembrar o nome', 'Na próxima visita, cumprimente essa pessoa pelo nome.', 1],
      ['Oferecer ajuda', 'Ofereça ajuda a alguém carregando algo pesado ou procurando um lugar.', 2],
      ['Avisar um desconhecido', 'Avise um desconhecido de algo: cadarço desamarrado, algo que caiu.', 2],
      ['Quem limpa', 'Agradeça quem faz a limpeza de um lugar que você frequenta.', 2],
      ['Falar com o gerente', 'Peça para falar com o gerente só para elogiar um atendente.', 1, 'o'],
      ['Gratidão atrasada', 'Mande mensagem agradecendo algo que alguém fez por você há tempos.', 1],
      ['Ceder o lugar', 'Ofereça seu lugar no transporte a quem precisa, falando em voz alta.', 2],
      ['O dia tá corrido?', 'Pergunte ao atendente: "e aí, o dia tá corrido?".', 3],
      ['Carta para você', 'Escreva uma carta curta para você, agradecendo tudo o que você já enfrentou até aqui.', 1, 'e'],
      ['Pagar um café', 'Pague um café ou um doce para alguém, sem motivo.', 1],
      ['Agradecer em público', 'Agradeça alguém na frente de outras pessoas: "valeu pela ajuda, Ana".', 2],
      ['E a viagem?', 'Pergunte a um conhecido sobre algo que ele te contou antes.', 2],
      ['Gentileza com ela', 'Segure a porta ou dê passagem a uma mulher e diga "pode passar", sorrindo.', 2],
      ['Vou lembrar de você', 'Diga a um atendente: "você me atendeu muito bem, vou lembrar de você".', 1],
      ['Posso ajudar?', 'Ao ver alguém perdido, pergunte: "posso ajudar?".', 1],
      ['Agradecer um líder', 'Agradeça pessoalmente um chefe ou professor por algo específico.', 1],
      ['Dia da gentileza', 'Faça 5 gentilezas diferentes num único dia.', 1],
    ]),

    chapter('voz', 'Voz e postura', '🎙️', 'Antes do que você diz, as pessoas ouvem como você diz.', [
      ['Ouvir sua voz', 'Grave um áudio de 30 segundos falando do seu dia e escute até o fim.', 1],
      ['Ler em voz alta', 'Leia uma página de livro em voz alta, devagar, com pausas.', 3],
      ['Respirar antes', 'Antes de uma conversa, respire fundo pela barriga duas vezes.', 3],
      ['Mais devagar', 'Numa interação inteira, fale mais devagar que o normal.', 3],
      ['Pedido claro', 'Faça um pedido num balcão em volume claro, de primeira.', 3],
      ['Frase que desce', 'Termine as frases com a voz descendo, não subindo como pergunta.', 3],
      ['Um segundo de pausa', 'Antes de responder algo, faça uma pausa de 1 segundo.', 3],
      ['Sem "tipo" e "né"', 'Converse 5 minutos tentando cortar "tipo", "né" e "é…".', 2],
      ['Mãos à mostra', 'Converse com as mãos fora do bolso, gesticulando com calma.', 3],
      ['Pés firmes', 'Numa conversa em pé, fique com os dois pés firmes, sem balançar.', 2],
      ['Sorriso na voz', 'Atenda uma ligação sorrindo e perceba o tom mudar.', 2],
      ['Ligar em vez de digitar', 'Ligue para um amigo ou parente em vez de mandar mensagem.', 2],
      ['Ligar para uma loja', 'Ligue para um estabelecimento e pergunte o horário de funcionamento.', 2],
      ['Pedido por telefone', 'Faça um pedido de comida por telefone, não pelo app.', 1],
      ['Áudio sem regravar', 'Mande um áudio de 1 minuto para um amigo, sem regravar.', 2],
      ['Assistir a si mesmo', 'Grave 1 minuto falando, assista e anote uma coisa boa sobre você.', 1],
      ['Ritmo com intenção', 'Conte algo devagar na parte importante e mais rápido no detalhe.', 2],
      ['Queixo erguido', 'Numa conversa, mantenha a cabeça erguida e o olhar no rosto da pessoa.', 3],
      ['Rir de verdade', 'Quando algo for engraçado, ria sem segurar.', 2],
      ['Seu nome com clareza', 'Ao se apresentar, diga seu nome devagar e claro.', 2],
      ['Seus valores', 'Escreva os 3 valores mais importantes para você e uma vez em que agiu de acordo com cada um.', 1, 'e'],
      ['Cantar alto', 'Cante uma música inteira em voz alta, sem vergonha.', 1],
      ['Falar para a câmera', 'Poste um story falando 15 segundos para a câmera.', 1, 'o'],
      ['Seu espaço cuidado', 'Arrume seu quarto: cama feita, roupas guardadas. Cuidar do seu espaço é se tratar com respeito.', 1, 'e'],
      ['Dois minutos de paixão', 'Grave você explicando por 2 minutos algo que você ama, olhando para a câmera.', 1],
    ]),

    chapter('pedidos', 'Pequenos pedidos', '❓', 'Pedir é se expor um pouco. Aqui você descobre que quase sempre dizem sim.', [
      ['Quanto custa?', 'Pergunte o preço de algo a um vendedor, mesmo que esteja escrito.', 3],
      ['Onde fica?', 'Pergunte a um funcionário onde fica um produto.', 3],
      ['Sem cebola', 'Peça algo com uma alteração: "sem cebola, por favor".', 2],
      ['As horas', 'Pergunte as horas a um desconhecido na rua.', 3],
      ['O caminho', 'Pergunte a um desconhecido como chegar a algum lugar.', 3],
      ['Pedir sem se desculpar', 'Peça algo que você quer sem começar com "desculpa incomodar".', 2, 'e'],
      ['Pode repetir?', 'Quando não entender algo, peça: "desculpa, pode repetir?".', 2],
      ['O que você recomenda?', 'Pergunte ao atendente: "o que você recomenda aqui?".', 3],
      ['Opinião de cliente', 'Numa loja, pergunte a outro cliente: "você já usou esse? é bom?".', 2],
      ['O sal da outra mesa', 'Peça algo emprestado à mesa vizinha: sal, guardanapo, ketchup.', 2],
      ['Uma caneta', 'Peça uma caneta emprestada a um desconhecido.', 2],
      ['Veio errado', 'Peça para trocar um pedido que veio errado, com calma.', 1],
      ['Tira uma foto minha?', 'Peça a um desconhecido para tirar uma foto sua.', 2],
      ['Perguntar a ela', 'Pergunte a uma mulher onde fica uma rua ou loja.', 3],
      ['Posso provar?', 'Peça para provar algo antes de comprar: sabor de sorvete, queijo.', 2],
      ['Desconto à vista', 'Pergunte: "tem desconto no Pix?".', 2],
      ['Fora do cardápio', 'Peça algo que não está no cardápio, com naturalidade.', 1],
      ['Uma tomada', 'Pergunte num estabelecimento se pode carregar o celular ali.', 1],
      ['Não, obrigado', 'Diga "não, obrigado" a um vendedor, sem justificar.', 3],
      ['Segunda pergunta', 'Faça uma pergunta e, depois da resposta, outra sobre o mesmo assunto.', 3],
      ['Dica de restaurante', 'Pergunte a alguém na rua: "conhece um lugar bom pra comer aqui perto?".', 2],
      ['Suas conquistas', 'Liste 10 coisas difíceis que você já superou na vida. Guarde a lista.', 1, 'e'],
      ['Dez por cento', 'Peça 10% de desconto em algo que não está em promoção.', 1, 'on'],
      ['Só um item', 'Peça para passar na frente na fila: "só tenho um item, posso?".', 1, 'on'],
      ['Pedido improvável', 'Peça algo improvável com bom humor: um refil grátis, uma amostra.', 1, 'on'],
    ]),

    chapter('balcao', 'Conversa de balcão', '🛒', 'Atendente tem papel definido e risco quase zero. É o melhor lugar para treinar.', [
      ['Hoje tá cheio, né?', 'Comente o movimento com o caixa.', 3],
      ['Há quanto tempo?', 'Pergunte ao atendente há quanto tempo ele trabalha ali.', 2],
      ['O favorito dele', 'Pergunte ao atendente qual o item favorito dele.', 3],
      ['Comentar a compra', 'Comente algo sobre o que está comprando: "esse aqui é o melhor da casa".', 3],
      ['Uma frase a mais', 'Quando perguntarem "tudo bem?", responda com uma frase a mais.', 3],
      ['Para que é', 'Conte ao vendedor para que é o que você está comprando.', 2],
      ['Na cadeira do barbeiro', 'Puxe assunto com o barbeiro ou cabeleireiro durante o corte.', 2],
      ['Papo na corrida', 'Puxe um assunto com o motorista durante a corrida.', 2],
      ['Como é o bairro?', 'Pergunte a um comerciante como é o bairro.', 2],
      ['Humor na espera', 'Faça um comentário bem-humorado sobre a espera com o atendente.', 2],
      ['Você atende bem', 'Diga ao atendente: "você atende muito bem".', 2],
      ['Foi um prazer', 'Quando alguém te agradecer, responda "foi um prazer", sem dizer "não foi nada".', 2, 'e'],
      ['Voltar ao assunto', 'Volte num lugar e retome com o mesmo atendente algo da conversa anterior.', 1],
      ['Você é daqui?', 'Pergunte ao garçom algo pessoal e leve: "você é daqui mesmo?".', 2],
      ['Um minuto no balcão', 'Converse 1 minuto com um atendente quando não houver fila.', 2],
      ['Com a atendente', 'Faça uma pergunta e um comentário a mais para uma atendente.', 3],
      ['A história do lugar', 'Pergunte ao dono de um comércio há quanto tempo o lugar existe.', 1],
      ['Ficou bom em mim?', 'Numa loja de roupa, pergunte: "essa ficou boa em mim?".', 2],
      ['Devolver a brincadeira', 'Quando o atendente brincar, devolva a brincadeira.', 2],
      ['Um presente para você', 'Compre ou faça algo de que você gosta só porque você merece, sem se justificar.', 1, 'e'],
      ['Recado ao cozinheiro', 'Peça para avisarem ao cozinheiro que o prato estava ótimo.', 1],
      ['Cliente conhecido', 'Vá ao mesmo lugar 3 vezes na semana e cumprimente o atendente como conhecido.', 1],
      ['Dois minutos de papo', 'Converse 2 minutos com um atendente sobre qualquer assunto.', 2],
      ['O nome dela', 'Pergunte o nome de uma atendente e use-o ao agradecer.', 2],
      ['O melhor cliente do dia', 'Seja o cliente mais simpático do dia de alguém: sorriso, nome, comentário, obrigado.', 1],
    ]),

    chapter('elogio-coisas', 'Elogiar coisas', '👟', 'Elogiar uma escolha é elogiar o gosto de alguém. Nunca constrange.', [
      ['O lugar', 'Diga ao atendente: "que lugar bonito".', 3],
      ['A comida', 'Diga "isso tá muito bom" a quem serviu.', 3],
      ['A música', 'Elogie a música que está tocando num estabelecimento.', 2],
      ['O capricho', 'Elogie o trabalho de alguém: "ficou caprichado".', 3],
      ['O cachorro', 'Elogie o cachorro de alguém na rua e pergunte o nome dele.', 3],
      ['A organização', 'Elogie um lugar arrumado para quem cuida dele.', 2],
      ['A máquina', 'Elogie o carro, a moto ou a bike de alguém.', 2],
      ['O livro', 'Pergunte a alguém se o livro que ele está lendo é bom.', 2],
      ['A tatuagem', 'Elogie uma tatuagem e pergunte o significado.', 2],
      ['O tênis dele', 'Elogie o tênis de um homem: "brabo esse tênis".', 3],
      ['O corte do amigo', 'Elogie o cabelo de um amigo ou colega.', 2],
      ['O prato do vizinho', 'Num restaurante, pergunte à mesa vizinha o que é o prato deles.', 1],
      ['Boa escolha', 'Elogie uma escolha de alguém: "boa escolha esse café".', 3],
      ['A estampa', 'Elogie a camiseta de banda, time ou estampa de alguém.', 2],
      ['O acessório', 'Elogie um relógio, mochila ou óculos de alguém.', 2],
      ['Onde comprou?', 'Elogie algo de alguém e pergunte onde a pessoa comprou.', 2],
      ['Mandei bem', 'Elogie em voz alta algo que você fez bem hoje: "mandei bem nisso".', 3, 'e'],
      ['O artista', 'Elogie uma arte de rua ou um artista trabalhando ao vivo.', 1],
      ['A habilidade', 'Elogie alguém fazendo algo bem: tocando, atendendo rápido, jogando.', 2],
      ['O óculos dela', 'Elogie o óculos, a bolsa ou um acessório de uma mulher.', 2],
      ['O livro dela', 'Pergunte a uma mulher se o livro que ela está lendo é bom.', 1],
      ['O tênis dela', 'Elogie o tênis de uma mulher: "seu tênis é muito bonito".', 2],
      ['O que veem em mim', 'Pergunte a 2 amigos qual qualidade eles mais veem em você e anote as respostas.', 1, 'eo'],
      ['O músico de rua', 'Elogie um músico de rua e pergunte o nome da música.', 1],
      ['Três elogios', 'Faça 3 elogios sinceros a pessoas diferentes num mesmo dia.', 1],
    ]),

    chapter('elogio-pessoas', 'Elogiar pessoas', '🌟', 'Agora o elogio é para a pessoa, não para a coisa. Específico vale mais que bonito.', [
      ['Em casa', 'Elogie algo em alguém da família: atitude, comida, jeito.', 3],
      ['Um amigo', 'Elogie uma qualidade de um amigo, olhando nos olhos.', 2],
      ['A roupa do amigo', 'Elogie a roupa de um amigo ou colega.', 3],
      ['A roupa de um desconhecido', 'Elogie a roupa de um homem desconhecido: "camisa massa".', 2],
      ['A atitude', 'Elogie a atitude de alguém: "foi muito legal o que você fez".', 2],
      ['A cor nela', 'Elogie a roupa de uma colega com leveza: "essa cor ficou ótima em você".', 2],
      ['O estilo', 'Diga a alguém: "você tem um estilo muito seu".', 2],
      ['A simpatia', 'Diga a uma atendente: "seu atendimento é muito simpático".', 2],
      ['O cabelo novo', 'Elogie o cabelo novo de uma colega ou conhecida.', 2],
      ['Elogiar e seguir', 'Elogie alguém e vá embora, sem esperar conversa.', 3],
      ['O casaco dela', 'Elogie a roupa de uma desconhecida e siga seu caminho: "seu casaco é muito bonito".', 2],
      ['O detalhe', 'Elogie um detalhe específico: "esse brinco combinou com a blusa".', 2],
      ['O caráter', 'Diga a alguém que você admira algo nela: paciência, humor, coragem.', 1],
      ['Na frente do grupo', 'Elogie alguém na frente de outras pessoas.', 1],
      ['Receber um elogio', 'Quando te elogiarem, diga só "obrigado, gostei de ouvir", sem diminuir.', 2],
      ['No espelho, com verdade', 'Olhe no espelho e diga uma coisa verdadeira de que você gosta em você.', 2, 'e'],
      ['O perfume', 'Diga a alguém: "que perfume bom, qual é?".', 1, 'o'],
      ['Onde ela comprou', 'Elogie a roupa de uma mulher e pergunte onde ela comprou.', 2],
      ['Caderno de elogios', 'Crie uma nota no celular com todo elogio que receber. Leia quando estiver mal.', 1, 'e'],
      ['Os olhos', 'Diga a uma amiga ou conhecida que os olhos dela são bonitos.', 1],
      ['Três desconhecidas', 'Elogie o estilo de 3 mulheres desconhecidas num dia, sem pedir nada em troca.', 1, 'o'],
      ['Elogiar e sustentar', 'Elogie alguém e mantenha o olhar enquanto a pessoa responde.', 2],
      ['Com o nome', 'Elogie alguém usando o nome: "Ana, você manda bem nisso".', 2],
      ['Do nada', 'Elogie um desconhecido no meio da rua: "você tá muito elegante hoje".', 1, 'o'],
      ['Dia do elogio', 'Faça 5 elogios sinceros num dia, a pelo menos 2 desconhecidos.', 1],
    ]),

    chapter('assunto', 'Puxar assunto', '💬', 'O objetivo não é ser interessante. É abrir a boca sem roteiro.', [
      ['O tempo', 'Comente o tempo com quem estiver do lado: "que calor hoje".', 3],
      ['A fila', 'Comente a fila com quem estiver perto: "anda rápido aqui, né?".', 3],
      ['No ponto', 'No ponto de ônibus, pergunte: "esse ônibus demora muito?".', 3],
      ['A cena engraçada', 'Comente algo engraçado que aconteceu no ambiente com quem estiver perto.', 2],
      ['No evento', 'Num evento, pergunte a alguém: "você conhece quem organizou?".', 2],
      ['O jogo', 'Comente um jogo ou notícia com alguém num bar ou padaria.', 2],
      ['Na academia', 'Pergunte a alguém quantas séries faltam no aparelho e comente algo.', 3],
      ['Uma dica de treino', 'Peça uma dica de exercício a alguém na academia.', 2],
      ['O colega calado', 'Puxe assunto com um colega com quem você nunca conversou.', 2],
      ['O que está ouvindo', 'Pergunte a alguém o que está ouvindo ou lendo.', 2],
      ['Com ela na fila', 'Comente algo do ambiente com uma mulher na fila.', 3],
      ['O cardápio', 'Pergunte a quem estiver do lado: "já comeu aqui? o que é bom?".', 2],
      ['O vizinho de assento', 'Puxe assunto com quem está ao seu lado no ônibus ou na sala de espera.', 2],
      ['Pergunta e comentário', 'Faça uma pergunta a um desconhecido e acrescente um comentário seu à resposta.', 3],
      ['Devolver a pergunta', 'Quando alguém puxar assunto com você, responda e devolva com uma pergunta.', 2],
      ['Sua opinião primeiro', 'Numa conversa, diga sua opinião antes de saber a dos outros.', 2, 'e'],
      ['Com ela na academia', 'Faça um comentário leve a uma mulher na academia, sem interromper o treino.', 1],
      ['Você é daqui?', 'Pergunte a um desconhecido: "você é daqui?".', 2],
      ['Prova contra a voz crítica', 'Quando pensar "sou um fracasso", escreva o pensamento e, ao lado, uma prova concreta contra ele.', 2, 'e'],
      ['Abrir afirmando', 'Comece com uma observação, não pergunta: "esse lugar sempre lota nesse horário".', 2],
      ['Uma roda inteira', 'Faça uma pergunta a um grupo de desconhecidos, por exemplo sobre o jogo no bar.', 1, 'o'],
      ['Ela sozinha', 'Puxe assunto com uma mulher sozinha num lugar calmo, comentando algo do ambiente.', 1],
      ['Três aberturas', 'Puxe assunto com 3 desconhecidos no mesmo dia.', 1],
      ['Pesquisa de rua', 'Pare alguém na rua e peça uma opinião rápida: "qual dessas duas cores?".', 1, 'on'],
      ['Cinco aberturas', 'Puxe assunto com 5 desconhecidos no mesmo dia.', 1, 'o'],
    ]),

    chapter('ousadias', 'Pequenas ousadias', '🎲', 'Coisas levemente esquisitas, feitas de propósito. O mundo liga muito menos do que você imagina.', [
      ['Uma peça diferente', 'Saia com uma roupa que chama um pouco mais de atenção que o seu normal.', 1],
      ['Cor forte', 'Use uma camiseta de cor forte o dia inteiro.', 1],
      ['Colecionar um não', 'Faça um pedido em que o não é provável, só para ver que nada acontece.', 2, 'n'],
      ['Sair sem comprar', 'Converse com um vendedor e saia sem comprar, agradecendo.', 2],
      ['Pergunta boba', 'Pergunte a um desconhecido algo que você já sabe, só pela interação.', 2],
      ['Sentar perto', 'Num lugar com espaço sobrando, sente perto de alguém em vez de longe.', 2],
      ['Aplaudir sozinho', 'Aplauda algo em público mesmo que ninguém comece.', 1],
      ['Pedir uma música', 'Peça uma música ao DJ ou ao músico de um bar.', 1],
      ['Evento sozinho', 'Vá a um evento, palestra ou show sozinho.', 1, 'o'],
      ['O melhor conselho', 'Pergunte a um desconhecido mais velho: "qual o melhor conselho que você já recebeu?".', 1, 'o'],
      ['Entrar no jogo', 'Peça para entrar numa partida de futebol, vôlei ou jogo de mesa com desconhecidos.', 1, 'on'],
      ['Dançar uma música', 'Dance uma música inteira em público: festa, bar ou show.', 1, 'o'],
      ['Programa só seu', 'Leve você mesmo a um programa que adora: cinema, parque, uma comida boa.', 1, 'e'],
      ['Janela aberta', 'Cante uma música com o vidro aberto, parado no trânsito.', 1, 'o'],
      ['Levantar a mão', 'Faça uma pergunta numa aula, palestra ou reunião.', 1],
      ['Pedir um abraço', 'Peça um abraço a um amigo próximo.', 1],
      ['Sua foto', 'Tire uma foto sua de que você goste e use como foto de perfil.', 1, 'eo'],
      ['Dizer não', 'Recuse com calma um pedido que você não quer atender.', 1],
      ['Discordar', 'Discorde de alguém numa conversa, com leveza.', 2],
      ['Acessório engraçado', 'Saia com algo divertido, como uma meia colorida à mostra, e use com orgulho.', 1, 'o'],
      ['Deitar na grama', 'Deite 5 minutos na grama de um parque movimentado.', 1, 'o'],
      ['Propor um brinde', 'Num bar ou festa, proponha um brinde ao grupo.', 1, 'o'],
      ['Me ensina?', 'Peça a um desconhecido para te ensinar algo que ele está fazendo.', 1, 'on'],
      ['Karaokê', 'Vá a um karaokê e cante uma música.', 1, 'o'],
      ['Dia do sim', 'Passe um dia dizendo sim a toda pequena oportunidade social que aparecer.', 1, 'o'],
    ]),

    chapter('conversa', 'Conversas de verdade', '🗣️', 'Agora a conversa precisa durar. O assunto acaba, e você continua mesmo assim.', [
      ['Um minuto', 'Mantenha uma conversa de 1 minuto com um desconhecido.', 3],
      ['Três perguntas', 'Numa conversa, faça 3 perguntas seguidas sobre a outra pessoa.', 3],
      ['Eu também!', 'Encontre algo em comum numa conversa e comente.', 2],
      ['Falar de você', 'Responda uma pergunta contando algo seu, além do básico.', 3],
      ['Aliás, qual seu nome?', 'No fim de uma conversa com um desconhecido, pergunte o nome dele.', 2],
      ['Prazer, eu sou…', 'Apresente-se a alguém: "prazer, eu sou o [seu nome]".', 3],
      ['Dois minutos', 'Converse 2 minutos com um desconhecido.', 3],
      ['Outro assunto', 'Quando o assunto acabar, puxe outro em vez de ir embora.', 2],
      ['Falando nisso…', 'Use algo que a pessoa disse para mudar de assunto: "falando em viagem…".', 2],
      ['Sair primeiro', 'Termine você a conversa: "foi bom conversar, até mais!".', 3],
      ['Cinco minutos com o colega', 'Converse 5 minutos com um colega sobre algo fora do trabalho.', 2],
      ['O que você faz?', 'Pergunte a um desconhecido com o que ele trabalha e o que mais gosta nisso.', 2],
      ['E fora do trabalho?', 'Pergunte: "o que você faz quando não está trabalhando?".', 2],
      ['Opinião sem pedir licença', 'Dê sua opinião sobre algo sem perguntar se a pessoa concorda.', 2],
      ['Três minutos', 'Mantenha uma conversa de 3 minutos com um desconhecido.', 2],
      ['Um minuto com ela', 'Converse 1 minuto com uma mulher desconhecida, num contexto natural.', 2],
      ['Dois no evento', 'Num evento, converse com 2 pessoas que você não conhece.', 1],
      ['Sem se diminuir', 'Passe um dia inteiro sem fazer piada se diminuindo nem se chamar de burro ou feio.', 2, 'e'],
      ['Terminar sua frase', 'Se te interromperem, termine o que estava dizendo: "só terminando…".', 1, 'e'],
      ['Cinco minutos', 'Converse 5 minutos com um desconhecido.', 1],
      ['Um novo amigo', 'Depois de uma conversa boa, troque contato para manter a amizade.', 1, 'n'],
      ['Almoço com o colega', 'Chame um colega para almoçar junto.', 1, 'n'],
      ['Entrar na dupla', 'Entre na conversa de duas pessoas e participe naturalmente.', 1, 'o'],
      ['O vizinho', 'Converse 5 minutos com um vizinho e descubra algo sobre ele.', 1],
      ['Marcar algo', 'Convide um conhecido para fazer algo: jogo, cinema, treino.', 1, 'n'],
    ]),

    chapter('historias', 'Contar histórias', '📖', 'Quem só responde perguntas nunca vira alguém memorável. Histórias fazem isso.', [
      ['Três histórias', 'Anote 3 histórias curtas da sua vida que você poderia contar.', 1],
      ['Ensaio', 'Conte uma delas em voz alta, sozinho, em 1 minuto.', 2],
      ['Sua superação', 'Escreva em 5 linhas um momento difícil que você atravessou e o que isso mostra sobre você.', 1, 'e'],
      ['Para um amigo', 'Conte uma história curta a um amigo.', 2],
      ['Começo, meio e fim', 'Conte algo do seu dia com começo, meio e fim.', 3],
      ['Um detalhe vivo', 'Conte uma história com um detalhe de cheiro, som ou cor.', 2],
      ['O que você sentiu', 'Conte uma história dizendo o que você sentiu naquela hora.', 2],
      ['Pausa antes do final', 'Conte uma história e faça uma pausa antes da parte principal.', 2],
      ['Seu vacilo', 'Conte um vacilo seu, rindo de si mesmo.', 2],
      ['Para um conhecido', 'Conte uma história curta a um colega ou conhecido.', 2],
      ['Nada de "normal"', 'Quando perguntarem do fim de semana, responda com uma mini-história.', 3],
      ['Para um desconhecido', 'Conte uma história curta a um desconhecido durante uma conversa.', 1],
      ['Com vozes', 'Numa história, imite a fala de alguém com outra voz.', 1],
      ['O que está aprendendo', 'Conte a alguém algo em que você está melhorando com dificuldade.', 1],
      ['Para a roda', 'Conte uma história engraçada para um grupo de 3 ou mais.', 1, 'o'],
      ['Orgulho em voz alta', 'Conte a alguém algo de que você se orgulha, sem minimizar.', 1, 'e'],
      ['Seu sonho', 'Conte a alguém algo que você quer realizar.', 1],
      ['O treino de coragem', 'Conte a alguém de confiança que você está treinando coragem social.', 1, 'o'],
      ['Gancho', 'Comece com uma frase que gere curiosidade: "você não vai acreditar no que aconteceu".', 2],
      ['Versão dois', 'Conte a mesma história para duas pessoas, melhorando na segunda.', 1],
      ['Dois minutos sem perder o fio', 'Conte uma história de 2 minutos sem se perder.', 1],
      ['Para ela', 'Conte uma história curta numa conversa com uma mulher.', 1],
      ['Uma puxa a outra', 'Depois que alguém contar uma história, conte uma sua parecida.', 2],
      ['Sua melhor', 'Grave sua melhor história em vídeo e assista.', 1],
      ['Prender a roda', 'Conte uma história numa roda de amigos, prendendo a atenção até o fim.', 1],
    ]),

    chapter('escuta', 'Perguntas que aprofundam', '🔍', 'A primeira pergunta é educação. A segunda é interesse. Carisma é fazer o outro se sentir ouvido.', [
      ['Sem interromper', 'Numa conversa, deixe a pessoa terminar todas as frases.', 3],
      ['O eco', 'Repita a última palavra que a pessoa disse, como pergunta, e veja ela continuar.', 2],
      ['Segundo nível', 'Depois da resposta, pergunte: "e o que te levou a isso?".', 3],
      ['Por quê?', 'Pergunte "por que você escolheu isso?" sobre uma decisão da pessoa.', 2],
      ['Três segundos', 'Depois da resposta, fique 3 segundos em silêncio, sem preencher.', 2],
      ['Então você diz que…', 'Resuma o que a pessoa disse com suas palavras.', 2],
      ['E como foi pra você?', 'Pergunte como a pessoa se sentiu quando ela contar algo.', 2],
      ['Você tinha falado…', 'Retome um detalhe que a pessoa disse antes.', 2],
      ['O que te anima?', 'Pergunte: "o que mais te anima ultimamente?".', 2],
      ['A melhor parte', 'Pergunte: "qual foi a melhor parte do seu dia?".', 2],
      ['Como você está', 'Escreva por 10 minutos como você está de verdade hoje, sem se julgar.', 2, 'e'],
      ['Se pudesse', 'Pergunte: "se pudesse fazer qualquer coisa, o que faria?".', 1],
      ['Faz todo sentido', 'Valide quando alguém se abrir: "imagino como foi".', 2],
      ['Uma surpresa', 'Faça perguntas até descobrir algo que te surpreenda na pessoa.', 1],
      ['Ouvir ela', 'Numa conversa com uma mulher, faça duas perguntas de segundo nível.', 1],
      ['Sem conselho', 'Quando alguém contar um problema, só escute e pergunte, sem aconselhar.', 2],
      ['O que importa', 'Pergunte: "o que é mais importante pra você hoje?".', 1],
      ['Vinte minutos sérios', 'Tenha uma conversa de 20 minutos com um amigo sobre algo sério.', 1],
      ['O que faria diferente', 'Pergunte a alguém mais velho o que ele faria diferente na vida.', 1],
      ['Celular guardado', 'Converse com alguém com o celular guardado o tempo inteiro.', 2],
      ['Do que eu preciso?', 'Pergunte a si mesmo "do que eu preciso agora?" e faça uma coisa que atenda a isso.', 2, 'e'],
      ['A paixão dela', 'Descubra numa conversa algo de que a pessoa é apaixonada.', 1],
      ['Olhar enquanto ouve', 'Mantenha o olhar enquanto a pessoa fala, desviando só às vezes.', 2],
      ['Posso perguntar?', 'Pergunte algo pessoal com delicadeza: "posso te perguntar uma coisa?".', 1],
      ['Dez minutos ouvindo', 'Converse 10 minutos com alguém recém-conhecido, mais ouvindo que falando.', 1],
    ]),

    chapter('humor', 'Humor e leveza', '😄', 'Levar a vida com leveza é o que faz as pessoas quererem ficar perto de você.', [
      ['Rir de si', 'Ria de um erro seu na frente de alguém.', 2],
      ['Comentário engraçado', 'Faça um comentário bem-humorado sobre uma situação do dia.', 2],
      ['Exagero', 'Use um exagero engraçado: "essa fila tá maior que a do banco no dia 5".', 2],
      ['Provocar um amigo', 'Provoque um amigo com carinho.', 2],
      ['Sério depois', 'Responda uma pergunta brincando primeiro e de verdade depois.', 2],
      ['Rir do erro, não de você', 'Quando errar, ria da situação e diga "acontece", em vez de se xingar.', 2, 'e'],
      ['Brincar no balcão', 'Faça uma brincadeira leve com um atendente.', 2],
      ['Uma piada', 'Conte uma piada curta a alguém.', 1],
      ['Ironia leve', 'Faça uma ironia leve sobre o ambiente com um desconhecido.', 1],
      ['Completar a piada', 'Quando alguém fizer graça, ria e complete a piada.', 2],
      ['Provocação com sorriso', 'Provoque um conhecido de leve e sustente o sorriso.', 2],
      ['A piada que volta', 'Retome uma piada que surgiu antes na mesma conversa.', 1],
      ['O nervoso assumido', 'Admita o nervosismo com humor: "tô treinando minha coragem, você é a cobaia".', 1, 'o'],
      ['Cara séria', 'Diga algo engraçado com a cara mais séria possível.', 1],
      ['Fazer ela sorrir', 'Faça um comentário engraçado sobre o ambiente para uma mulher.', 1],
      ['Provocar uma amiga', 'Provoque com carinho uma amiga ou conhecida.', 1],
      ['Aposto que…', 'Desafie alguém de brincadeira: "aposto que você nunca…".', 1],
      ['Não com humor', 'Ao ouvir um não, responda com uma brincadeira leve e saia sorrindo.', 1, 'n'],
      ['Imitação', 'Faça uma imitação engraçada numa roda de amigos.', 1, 'o'],
      ['Rir alto em público', 'Ria alto de algo engraçado num lugar público.', 1],
      ['Você tem cara de…', 'Brinque com alguém: "você tem cara de quem sempre chega atrasado".', 1],
      ['Devolver a provocação', 'Quando te provocarem, devolva com leveza em vez de se defender.', 1],
      ['Bom com você', 'No fim do dia, anote um momento em que você foi bom com você mesmo.', 2, 'e'],
      ['Provocar ela', 'Faça uma provocação leve a uma mulher numa conversa que já está boa.', 1],
      ['Dia leve', 'Passe um dia inteiro procurando o lado engraçado de cada interação.', 1],
    ]),

    chapter('grupos', 'Grupos e palco', '👥', 'Falar para várias pessoas assusta mais. Por isso vem depois de você já saber conversar.', [
      ['Uma frase na reunião', 'Fale uma frase numa reunião, aula ou grupo.', 2],
      ['Rir com o grupo', 'Ria junto com o grupo em vez de sorrir calado.', 2],
      ['Sua opinião', 'Dê sua opinião numa conversa em grupo.', 2],
      ['Pergunta para todos', 'Faça uma pergunta para o grupo inteiro responder.', 2],
      ['Entrar na roda', 'Chegue numa roda de conhecidos e entre na conversa.', 2],
      ['Contar para três', 'Conte algo curto para um grupo de 3 ou mais.', 2],
      ['Falar primeiro', 'Numa reunião ou aula, seja o primeiro a falar.', 1],
      ['Apresentar duas pessoas', 'Apresente duas pessoas que não se conhecem.', 1],
      ['Um minuto na reunião', 'Fale 1 minuto seguido numa reunião ou aula.', 1],
      ['Organizar o encontro', 'Organize um encontro de amigos.', 1],
      ['Roda de desconhecidos', 'Numa festa ou evento, chegue numa roda e se apresente.', 1, 'o'],
      ['Assunto novo', 'Quando a conversa do grupo morrer, puxe um assunto novo.', 1],
      ['Brinde curto', 'Faça um brinde curto num encontro.', 1, 'o'],
      ['Três minutos de apresentação', 'Apresente algo de 3 minutos a um grupo.', 1],
      ['Aula nova', 'Faça uma aula em grupo nova, como dança, teatro ou luta, e converse com alguém lá.', 1, 'o'],
      ['Grupo misto', 'Converse num grupo com homens e mulheres, falando pelo menos 3 vezes.', 1],
      ['Sem pedir licença para falar', 'Num grupo, fale sem começar com "deve ser bobeira, mas…".', 2, 'e'],
      ['Anfitrião', 'Receba amigos e apresente as pessoas entre si.', 1],
      ['Homenagem', 'Fale algo em homenagem a alguém num aniversário ou encontro.', 1, 'o'],
      ['Improviso', 'Faça uma aula de teatro ou improviso.', 1, 'o'],
      ['Microfone', 'Fale ao microfone em algum lugar: karaokê, evento, microfone aberto.', 1, 'o'],
      ['Não sem desculpa', 'Diga não a um convite que você não quer, sem inventar desculpa.', 1, 'e'],
      ['Encontro de interesse', 'Vá a um encontro de pessoas com um interesse em comum e converse com 3 delas.', 1, 'o'],
      ['Decidir pelo grupo', 'Assuma a decisão do grupo: onde comer, o que fazer.', 1],
      ['Todos ouvindo', 'Conte uma história para um grupo grande, com todos prestando atenção.', 1, 'o'],
    ]),

    chapter('elas', 'Mulheres, sem pressão', '🌸', 'Ninguém aqui está flertando. Você só aprende que falar com uma mulher é igual a falar com qualquer pessoa.', [
      ['Sorrir para ela', 'Cruze o olhar com uma mulher e sorria, sem dizer nada.', 3],
      ['Bom dia a ela', 'Diga bom dia a uma mulher num contexto natural.', 3],
      ['Uma pergunta prática', 'Pergunte as horas ou um caminho a uma mulher.', 3],
      ['Obrigado, com nome', 'Agradeça uma atendente pelo nome, sorrindo.', 3],
      ['Comentário na fila', 'Comente algo do ambiente com uma mulher na fila.', 2],
      ['A recomendação dela', 'Pergunte a uma vendedora o que ela recomenda.', 2],
      ['A colega', 'Puxe assunto com uma colega com quem você fala pouco.', 2],
      ['Pedir ajuda a ela', 'Peça ajuda a uma mulher para algo: escolher um presente, achar um lugar.', 2],
      ['O que você oferece', 'Escreva 5 coisas boas que uma mulher ganharia convivendo com você.', 1, 'e'],
      ['Um minuto com ela', 'Converse 1 minuto com uma mulher desconhecida sobre o ambiente.', 2],
      ['Devolver a ela', 'Quando uma mulher falar com você, responda e devolva com uma pergunta.', 2],
      ['Olhar enquanto fala', 'Fale com uma mulher olhando nos olhos dela o tempo todo.', 2],
      ['A que você acha bonita', 'Faça uma pergunta prática a uma mulher que você acha bonita.', 2, 'k'],
      ['O objeto dela', 'Elogie a bolsa, o livro ou o tênis de uma mulher.', 2],
      ['De igual para igual', 'Converse com uma mulher bonita sem se encolher e sem bajular: de igual para igual.', 2, 'e'],
      ['Na academia', 'Pergunte a uma mulher na academia se ela vai usar o aparelho e comente algo.', 1],
      ['Trocar nomes', 'Numa conversa leve, pergunte o nome dela e diga o seu.', 1],
      ['Dois minutos com ela', 'Converse 2 minutos com uma mulher desconhecida.', 1],
      ['Algo seu', 'Numa conversa com uma mulher, conte algo seu.', 1],
      ['Fazer ela rir', 'Faça uma mulher rir com um comentário leve.', 1],
      ['Ela sozinha, no café', 'Puxe assunto com uma mulher sozinha num lugar calmo, a partir de algo do ambiente.', 1],
      ['A mais bonita do lugar', 'Faça uma pergunta simples à mulher que mais chamou sua atenção.', 1, 'ok'],
      ['Três num dia', 'Converse com 3 mulheres diferentes num dia, sobre qualquer coisa.', 1],
      ['Tchau, com nome', 'Ao terminar uma conversa com uma mulher, despeça-se pelo nome dela.', 1],
      ['Cinco minutos com ela', 'Converse 5 minutos com uma mulher que você acabou de conhecer.', 1],
    ]),

    chapter('com-ela', 'Conversa com ela', '💭', 'Tudo que você já treinou, agora com ela: perguntas, histórias, humor, opinião.', [
      ['Segundo nível com ela', 'Numa conversa com uma mulher, faça uma pergunta de segundo nível.', 2],
      ['Algo em comum', 'Encontre algo em comum com uma mulher numa conversa.', 2],
      ['Uma história para ela', 'Conte uma mini-história sua numa conversa com uma mulher.', 2],
      ['Discordar dela', 'Dê uma opinião diferente da dela, com leveza.', 1],
      ['Brincar com ela', 'Faça uma provocação leve e brincalhona numa conversa com uma mulher.', 1],
      ['O que ela faz', 'Pergunte o que ela faz e o que mais gosta nisso.', 2],
      ['Você disse que…', 'Retome um detalhe que ela disse antes, mostrando que ouviu.', 2],
      ['A roupa dela', 'Elogie a roupa de uma mulher numa conversa que já começou.', 2],
      ['Abrir no app', 'Abra uma conversa num app de encontros com uma pergunta sobre algo do perfil dela.', 2],
      ['Sem mendigar atenção', 'Se ela demorar a responder, não mande mensagem dupla. Siga seu dia.', 2, 'e'],
      ['No café', 'Converse com uma mulher num café ou livraria por 3 minutos.', 1],
      ['Sair em alta', 'Encerre você a conversa com ela, em alta: "foi ótimo conversar".', 2],
      ['Na festa', 'Numa festa, puxe assunto com uma mulher.', 1],
      ['O sonho dela', 'Pergunte a uma mulher o que ela adoraria fazer um dia.', 1],
      ['Seu ponto fraco', 'Conte a uma mulher algo em que você é ruim, rindo.', 1],
      ['O que foi corajoso', 'Depois de uma conversa que não fluiu, anote o que você fez de corajoso nela.', 1, 'e'],
      ['Evento ou aula', 'Num evento ou aula, converse com uma mulher que você não conhece.', 1, 'o'],
      ['Depois da apresentação', 'Quando te apresentarem uma mulher, converse com ela por 3 minutos.', 1],
      ['Dez minutos', 'Converse 10 minutos com uma mulher que você acabou de conhecer.', 1],
      ['Só pelo prazer', 'Tenha uma conversa boa com uma mulher e vá embora sem pedir contato.', 1],
      ['Olhar e sorrir', 'Numa conversa com ela, sustente o olhar enquanto ela fala e sorria.', 2],
      ['Duas risadas', 'Faça uma mulher rir duas vezes na mesma conversa.', 1],
      ['Mesma direção', 'De dia, em lugar tranquilo, puxe assunto com uma mulher indo na mesma direção. Se ela não quiser papo, deseje um bom dia e siga.', 1, 'o'],
      ['Caminho e comentário', 'Pergunte um caminho a uma mulher na rua e continue com um comentário.', 1, 'o'],
      ['Dia social', 'Converse com 5 mulheres diferentes num mesmo dia.', 1, 'o'],
    ]),

    chapter('flerte', 'Flerte', '😏', 'Flertar é mostrar interesse e deixar ela livre para responder. Sinal de desinteresse: recue sorrindo.', [
      ['Dois segundos a mais', 'Sustente o olhar de uma mulher 2 segundos além do confortável e sorria.', 3],
      ['Sorriso com intenção', 'Sorria para uma mulher deixando claro que gostou de olhar.', 2],
      ['Você é muito bonita', 'Numa conversa, diga olhando nos olhos: "você é muito bonita".', 1, 'n'],
      ['Elogio fora do óbvio', 'Faça um elogio criativo: "você tem um jeito de sorrir que dá vontade de conversar".', 1],
      ['Mais devagar', 'Numa conversa com ela, fale mais devagar e com pausas.', 2],
      ['Provocar com charme', 'Provoque de leve: "você tem cara de quem escolhe mal o filme".', 1],
      ['Gostei de conversar', 'Diga a uma mulher: "gostei muito de conversar com você".', 1],
      ['Ela está sozinha?', 'Pergunte com leveza se ela está acompanhada ou solteira.', 1, 'n'],
      ['Flerte no app', 'Mande uma mensagem com um elogio criativo e uma pergunta.', 2],
      ['Um minuto de flerte', 'Flerte por 1 minuto e encerre você, em alta.', 1],
      ['Um passo mais perto', 'Numa conversa boa, chegue um pouco mais perto e observe se ela fica confortável.', 1],
      ['O jeito que ela pensa', 'Elogie algo que ela disse: "gostei do jeito que você pensa".', 1],
      ['Por que sair comigo', 'Escreva por que alguém gostaria de sair com você. Leia antes de flertar.', 1, 'e'],
      ['Dois minutos de flerte', 'Flerte por 2 minutos e encerre em alta.', 1],
      ['Precisava te dizer', 'Diga a uma desconhecida, num lugar tranquilo: "te achei muito bonita, queria te dizer isso".', 1, 'on'],
      ['Ler os sinais', 'Numa conversa, repare se ela sorri, pergunta de volta e fica. Anote depois.', 1],
      ['Recuar com elegância', 'Ao perceber desinteresse, encerre sorrindo: "foi bom te conhecer".', 1, 'n'],
      ['Flerte na festa', 'Numa festa, flerte com uma mulher por 3 minutos.', 1],
      ['Fazer ela rir no flerte', 'Faça ela rir com uma provocação leve durante o flerte.', 1],
      ['Elogiar e ir', 'Elogie uma mulher e vá embora sem pedir nada, sorrindo.', 1, 'o'],
      ['Sem pedir aprovação', 'Flerte sem perguntar "tô incomodando?". Se ela não quiser, ela vai mostrar, e você recua.', 1, 'e'],
      ['Queria te ver de novo', 'Diga a ela: "queria te ver de novo".', 1, 'n'],
      ['Silêncio com sorriso', 'Numa conversa, segure o olhar em silêncio por 3 segundos e sorria.', 1],
      ['Duas no mesmo dia', 'Flerte com duas mulheres diferentes no mesmo dia.', 1, 'o'],
      ['Cinco minutos de flerte', 'Mantenha um flerte leve por 5 minutos e encerre em alta.', 1],
    ]),

    chapter('cantadas', 'Cantadas e abordagens', '🔥', 'Cantada boa é engraçada e respeitosa, nunca sobre o corpo. A meta é fazer ela sorrir. Um não encerra a abordagem.', [
      ['Cinco cantadas', 'Escreva 5 cantadas engraçadas e respeitosas e leia em voz alta.', 1],
      ['Comemorar a tentativa', 'Depois de cada abordagem, se dê uma recompensa pequena, seja qual for o resultado.', 2, 'e'],
      ['Cantada no app', 'Use uma cantada engraçada para abrir uma conversa no app.', 2],
      ['Rir de si', 'Use uma cantada rindo de você mesmo: "ia te pedir uma informação, mas esqueci o que era".', 1, 'n'],
      ['Sobre o lugar', 'Use uma cantada sobre o ambiente: "esse café ficou mais bonito agora".', 1, 'n'],
      ['Um não não é sobre você', 'Depois de um não, escreva: "foi sobre o momento dela, não sobre o meu valor".', 1, 'e'],
      ['Sem cantada', 'Diga sorrindo: "não tenho cantada boa, mas queria te conhecer".', 1, 'n'],
      ['Me ajuda a decidir?', 'Aborde uma mulher com uma pergunta divertida: "me ajuda a decidir uma coisa?".', 1, 'n'],
      ['Trinta segundos', 'Aborde uma desconhecida, converse 30 segundos e saia sorrindo.', 1, 'on'],
      ['Depois da risada', 'Use uma cantada e, depois que ela rir, continue a conversa.', 1, 'n'],
      ['De dia', 'Aborde uma mulher de dia, num lugar calmo, dizendo que ela chamou sua atenção.', 1, 'on'],
      ['Na livraria', 'Comente o livro que uma mulher está olhando e faça um elogio.', 1, 'on'],
      ['Na festa', 'Aborde uma mulher numa festa e se apresente.', 1, 'on'],
      ['Grupo de amigas', 'Aborde um grupo de amigas com uma pergunta divertida e converse com todas.', 1, 'on'],
      ['Sua melhor cantada', 'Use sua melhor cantada olhando nos olhos e sustente o sorriso.', 1, 'on'],
      ['Agradecer o não', 'Ao ouvir um não, diga "valeu, boa noite!" em 5 segundos e saia de cabeça erguida.', 1, 'n'],
      ['Dois minutos', 'Aborde uma desconhecida, converse 2 minutos e encerre você.', 1, 'on'],
      ['Três abordagens', 'Faça 3 abordagens num dia, sem se importar com o resultado.', 1, 'on'],
      ['O bilhete', 'Num café, deixe um bilhete gentil e engraçado para uma mulher, sem esperar resposta.', 1, 'on'],
      ['A que te intimida', 'Aborde uma mulher que você acha "demais pra você".', 1, 'on'],
      ['Na rua', 'De dia e com calma, diga a uma mulher na rua: "te vi passar e quis dizer oi".', 1, 'on'],
      ['Só o essencial', 'Aborde só com: "oi, te achei interessante. Qual seu nome?".', 1, 'on'],
      ['Depois do não', 'Depois de ouvir um não, faça outra abordagem com outra pessoa no mesmo dia.', 1, 'on'],
      ['Cinco abordagens', 'Faça 5 abordagens num dia.', 1, 'on'],
      ['Intenção total', 'Aborde, flerte, faça ela rir e diga claramente que gostou dela.', 1, 'on'],
    ]),

    chapter('convite', 'Contato e convite', '💌', 'Um "não" encerra o assunto, sem insistir. Cada convite feito é vitória, seja qual for a resposta.', [
      ['Instagram em grupo', 'Peça o Instagram de alguém que você conheceu numa roda de amigos.', 2, 'n'],
      ['WhatsApp pelo app', 'No app, depois de uma boa conversa, peça o WhatsApp.', 2, 'n'],
      ['O número dela', 'Depois de uma conversa boa, peça o número dela pessoalmente.', 2, 'n'],
      ['Primeira mensagem', 'Mande mensagem no mesmo dia, citando um detalhe da conversa.', 2],
      ['Manter o fio', 'Converse por mensagem por 3 dias, com pelo menos uma brincadeira.', 1],
      ['Dia e hora', 'Convide para um café propondo dia e hora específicos.', 2, 'n'],
      ['Convite casual', 'Convide para algo simples: "vou naquele café sábado, bora?".', 1, 'n'],
      ['Ouvir não ao convite', 'Se o convite for recusado, responda com leveza e não insista.', 1, 'n'],
      ['Primeiro encontro', 'Vá a um encontro de café de 1 hora.', 1],
      ['Conduzir', 'No encontro, faça perguntas de segundo nível e conte uma história sua.', 1],
      ['Dizer o que gostou', 'No encontro, diga algo que você gostou nela.', 1],
      ['Você também escolhe', 'No encontro, repare se você gosta dela, não só se ela gosta de você.', 1, 'e'],
      ['Terminar em alta', 'Termine o encontro enquanto está bom: "adorei, vamos repetir".', 1],
      ['Mensagem depois', 'Mande mensagem no mesmo dia dizendo que gostou do encontro.', 1],
      ['Segundo encontro', 'Convide para um segundo encontro com uma ideia concreta.', 1, 'n'],
      ['Conheceu hoje', 'Convide uma mulher que você conheceu no mesmo dia para um café em outro dia.', 1, 'on'],
      ['Agora mesmo', 'Numa conversa boa, convide na hora: "vamos tomar um café agora?".', 1, 'on'],
      ['Contato na rua', 'Aborde, converse e peça o contato de uma desconhecida.', 1, 'on'],
      ['Encontro ativo', 'Num segundo encontro, faça algo ativo: caminhada, exposição, jogo.', 1],
      ['Dizer o que sente', 'Diga a alguém com quem você está saindo que gosta da companhia dela.', 1],
      ['Quem você se tornou', 'Releia suas conquistas e escreva quem você é hoje, comparado a quem começou esta trilha.', 1, 'e'],
      ['Quem você gosta', 'Convide aquela mulher de quem você gosta de verdade.', 1, 'on'],
      ['Posso te beijar?', 'Num encontro bom e com sinais claros dela, pergunte se pode beijá-la.', 1, 'on'],
      ['Contato antigo', 'Mande mensagem para alguém com quem perdeu contato e convide para algo.', 1, 'n'],
      ['O impensável', 'Faça o convite que, no começo desta trilha, seria impensável para você.', 1, 'on'],
    ]),
  ],
}
